name: Docker Build & OWASP ZAP Scan

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t python-app:latest .

      # Run Docker container
      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name python-app python-app:latest

      # Wait for server to start
      - name: Wait for server
        run: sleep 15

      # OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://localhost:8000"
          cmd_options: "-a"
          artifact_name: "zap-report"

      # Upload ZAP HTML Report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
